# Generated by Django 2.2.4 on 2019-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('key', models.CharField(max_length=100, verbose_name='Chave')),
                ('app', models.CharField(max_length=100, verbose_name='Aplicação')),
            ],
            options={
                'db_table': 'chaves',
            },
        ),
    ]
