# Generated by Django 2.2.4 on 2019-08-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chave'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chave',
            table='chave',
        ),
    ]
