# Generated by Django 2.2.4 on 2019-08-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome',
            },
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Nome'},
        ),
    ]
