# Generated by Django 2.2.4 on 2019-08-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190829_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
